---@meta

---@class RuntimeContext_DCGetSet
---@field getters InstrumentTarget[] Instruments to read from
---@field setters InstrumentTarget[] Instruments to write to
---@field setVoltages table<string, number> Voltages to set (indexed by InstrumentTarget.serialize)
---@field sampleRate number Sampling rate in Hz
---@field numPoints integer Number of points to acquire
---@field call fun(funcName: string, ...): any Call an instrument command or system function
---@field parallel fun(block: function) Execute a block of commands in parallel
---@field log fun(msg: string) Log a message
